_BASE_: "../Base-RCNN-FPN-DCT.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: CascadeROIHeads
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",) # "lvis_v0.5_val_cocofied")
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (210000, 250000)
  MAX_ITER: 270000
OUTPUT_DIR: "output/DCT_casecade_R101_3x_mask128x128_300_l1_007_4conv.yaml"

